{% set name = "execnb" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/execnb-{{ version }}.tar.gz
  sha256: 2d6581d6f052568287f0748b80ead01c1ed698528f336bcfa8c8630b01e9668a

build:
  entry_points:
    - exec_nb=execnb.shell:exec_nb
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - fastcore >=1.5.5
    - ipython

test:
  imports:
    - execnb
  commands:
    - pip check
    - exec_nb --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://fastai.github.io/execnb/
  dev_url: https://github.com/fastai/execnb
  summary: Execute a jupyter notebook, fast, without needing jupyter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
