{% set name = "execnb" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/execnb-{{ version }}.tar.gz
  sha256: 64f4aea889125679800351d834c50e4f0fb9025f612b1a346503ef9d5b218312

build:
  entry_points:
    - exec_nb=execnb.shell:exec_nb
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - fastcore >=1.5.5
    - ipython

test:
  imports:
    - execnb
  commands:
    - pip check
    - exec_nb --help
  requires:
    - pip

about:
  home: https://fastai.github.io/execnb/
  dev_url: https://github.com/fastai/execnb
  summary: Execute a jupyter notebook, fast, without needing jupyter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
