{% set name = "execnb" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/execnb-{{ version }}.tar.gz
  sha256: d6df5b5e3858d70a88a40a4c73f702d72f212147bb4077a7b60165c6e6c0b009

build:
  entry_points:
    - exec_nb=execnb.shell:exec_nb
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64.0
  run:
    - python >={{ python_min }}
    - fastcore >=1.5.5
    - ipython

test:
  imports:
    - execnb
  commands:
    - pip check
    - exec_nb --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://fastai.github.io/execnb/
  dev_url: https://github.com/fastai/execnb
  summary: Execute a jupyter notebook, fast, without needing jupyter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
