schema_version: 1

context:
  name: execnb
  version: "0.2.8"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/execnb-${{ version }}.tar.gz
  sha256: fca5daaaea5e7611073c530aa7c2f62d87e31b3a792e0e7d86a0fd3305410021

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - exec_nb=execnb.shell:exec_nb

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=64
  run:
    - python >=${{ python_min }}
    - fastcore >=2.1.2
    - ipython

tests:
  - python:
      imports:
        - execnb
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - exec_nb --help

about:
  summary: Execute a jupyter notebook, fast, without needing jupyter
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://fastai.github.io/execnb/
  repository: https://github.com/fastai/execnb

extra:
  recipe-maintainers:
    - thewchan
