schema_version: 1

context:
  name: execnb
  version: "0.1.16"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/execnb-${{ version }}.tar.gz
  sha256: 66c9c009c6ba030bfd0c0f6a71ee4d856a1d8efc4306fe9a8c15370c0645000c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - exec_nb=execnb.shell:exec_nb

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=64.0
  run:
    - python >=${{ python_min }}
    - fastcore >=1.5.5
    - ipython

tests:
  - python:
      imports:
        - execnb
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - exec_nb --help

about:
  summary: Execute a jupyter notebook, fast, without needing jupyter
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://fastai.github.io/execnb/
  repository: https://github.com/fastai/execnb

extra:
  recipe-maintainers:
    - thewchan
